-- ════════════════════════════════════════════════════════════════════
-- Update ALL remaining email templates to CRM design + brand palette
-- Date: 2026-09-17
--
-- 9 templates were updated in the 2026-09-11 CRM redesign migration.
-- 1 template (checklist_expiry_reminder) was updated in 2026-09-17.
-- This migration updates the remaining 17 templates.
--
-- All templates now use the same CRM design:
--   - Teal header (#174A43) with terracotta eyebrow label (#D98F78)
--   - White card on ivory background (#F7F3E8)
--   - Charcoal text (#263633) + sage secondary (#5C6B66)
--   - Brand teal CTA button (#174A43)
--   - Footer with HIPAA/256-bit/BAA trust signals
--
-- Run in Supabase SQL Editor. Idempotent — safe to re-run.
-- ════════════════════════════════════════════════════════════════════

BEGIN;

-- Helper: CRM HTML wrapper function (inline for each template)
-- Each UPDATE follows the same pattern: teal header + white card + CTA + footer

-- 1. account_approval
UPDATE "EmailTemplate" SET
  subject = 'Your account has been approved',
  body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#F7F3E8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#263633;line-height:1.6;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#F7F3E8;"><tr><td align="center" style="padding:32px 16px;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;width:100%;background-color:#FFFFFF;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(23,74,67,0.06);border:1px solid #E5DFCF;"><tr><td style="background-color:#174A43;padding:28px 32px;text-align:center;"><div style="font-family:Georgia,serif;font-size:24px;font-weight:700;color:#FFFFFF;letter-spacing:-0.5px;">MyZipVault</div><div style="font-size:11px;font-weight:600;color:#D98F78;letter-spacing:2.5px;text-transform:uppercase;margin-top:6px;">Account Approved</div></td></tr><tr><td style="padding:36px;font-size:15px;color:#263633;"><p style="margin:0 0 16px;">Hello {{user_name}},</p><p style="margin:0 0 16px;color:#5C6B66;">Your account has been approved. You can now log in and start using MyZipVault.</p><div style="text-align:center;margin:28px 0;"><a href="{{login_link}}" style="background-color:#174A43;color:#FFFFFF;padding:14px 32px;border-radius:10px;text-decoration:none;font-weight:600;display:inline-block;font-size:15px;">Log In</a></div></td></tr><tr><td style="padding:0 36px 20px;"><table width="100%" style="border-top:1px solid #E5DFCF;padding-top:20px;"><tr><td style="font-size:12px;color:#8B9994;text-align:center;">You received this email because your MyZipVault account was approved.<br>HIPAA Aligned · 256-bit Encryption · BAA Available</td></tr></table></td></tr></table></td></tr></table></body></html>'
WHERE template_key = 'account_approval';

-- 2. account_suspension_confirmation
UPDATE "EmailTemplate" SET
  subject = 'Your account has been suspended',
  body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#F7F3E8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#263633;line-height:1.6;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#F7F3E8;"><tr><td align="center" style="padding:32px 16px;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;width:100%;background-color:#FFFFFF;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(23,74,67,0.06);border:1px solid #E5DFCF;"><tr><td style="background-color:#174A43;padding:28px 32px;text-align:center;"><div style="font-family:Georgia,serif;font-size:24px;font-weight:700;color:#FFFFFF;">MyZipVault</div><div style="font-size:11px;font-weight:600;color:#D98F78;letter-spacing:2.5px;text-transform:uppercase;margin-top:6px;">Account Suspended</div></td></tr><tr><td style="padding:36px;font-size:15px;color:#263633;"><p style="margin:0 0 16px;">Hello {{user_name}},</p><p style="margin:0 0 16px;color:#5C6B66;">Your MyZipVault account has been suspended. If you believe this is an error, please contact support.</p><p style="margin:0 0 16px;color:#5C6B66;">Reason: {{reason}}</p></td></tr><tr><td style="padding:0 36px 20px;"><table width="100%" style="border-top:1px solid #E5DFCF;padding-top:20px;"><tr><td style="font-size:12px;color:#8B9994;text-align:center;">HIPAA Aligned · 256-bit Encryption · BAA Available</td></tr></table></td></tr></table></td></tr></table></body></html>'
WHERE template_key = 'account_suspension_confirmation';

-- 3. baa_expiry
UPDATE "EmailTemplate" SET
  subject = 'Your BAA is expiring soon',
  body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#F7F3E8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#263633;line-height:1.6;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#F7F3E8;"><tr><td align="center" style="padding:32px 16px;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;width:100%;background-color:#FFFFFF;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(23,74,67,0.06);border:1px solid #E5DFCF;"><tr><td style="background-color:#174A43;padding:28px 32px;text-align:center;"><div style="font-family:Georgia,serif;font-size:24px;font-weight:700;color:#FFFFFF;">MyZipVault</div><div style="font-size:11px;font-weight:600;color:#D98F78;letter-spacing:2.5px;text-transform:uppercase;margin-top:6px;">BAA Expiring</div></td></tr><tr><td style="padding:36px;font-size:15px;color:#263633;"><p style="margin:0 0 16px;">Hello {{admin_name}},</p><p style="margin:0 0 16px;color:#5C6B66;">Your Business Associate Agreement (BAA) will expire on <strong style="color:#174A43;">{{expiry_date}}</strong>. Please renew it to maintain HIPAA compliance.</p><div style="text-align:center;margin:28px 0;"><a href="{{login_link}}" style="background-color:#174A43;color:#FFFFFF;padding:14px 32px;border-radius:10px;text-decoration:none;font-weight:600;display:inline-block;font-size:15px;">Review BAA</a></div></td></tr><tr><td style="padding:0 36px 20px;"><table width="100%" style="border-top:1px solid #E5DFCF;padding-top:20px;"><tr><td style="font-size:12px;color:#8B9994;text-align:center;">HIPAA Aligned · 256-bit Encryption · BAA Available</td></tr></table></td></tr></table></td></tr></table></body></html>'
WHERE template_key = 'baa_expiry';

-- 4. consent_share_notification
UPDATE "EmailTemplate" SET
  subject = 'Your document has been shared',
  body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#F7F3E8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#263633;line-height:1.6;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#F7F3E8;"><tr><td align="center" style="padding:32px 16px;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;width:100%;background-color:#FFFFFF;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(23,74,67,0.06);border:1px solid #E5DFCF;"><tr><td style="background-color:#174A43;padding:28px 32px;text-align:center;"><div style="font-family:Georgia,serif;font-size:24px;font-weight:700;color:#FFFFFF;">MyZipVault</div><div style="font-size:11px;font-weight:600;color:#D98F78;letter-spacing:2.5px;text-transform:uppercase;margin-top:6px;">Document Shared</div></td></tr><tr><td style="padding:36px;font-size:15px;color:#263633;"><p style="margin:0 0 16px;">Hello {{candidate_name}},</p><p style="margin:0 0 16px;color:#5C6B66;">Your <strong style="color:#174A43;">{{document_type}}</strong> has been shared with <strong style="color:#174A43;">{{recruiter_name}}</strong>. The sharing expires on <strong>{{expiry_date}}</strong>.</p><div style="text-align:center;margin:28px 0;"><a href="{{login_link}}" style="background-color:#174A43;color:#FFFFFF;padding:14px 32px;border-radius:10px;text-decoration:none;font-weight:600;display:inline-block;font-size:15px;">Manage Sharing</a></div></td></tr><tr><td style="padding:0 36px 20px;"><table width="100%" style="border-top:1px solid #E5DFCF;padding-top:20px;"><tr><td style="font-size:12px;color:#8B9994;text-align:center;">HIPAA Aligned · 256-bit Encryption · BAA Available</td></tr></table></td></tr></table></td></tr></table></body></html>'
WHERE template_key = 'consent_share_notification';

-- 5. credential_expiry_warning
UPDATE "EmailTemplate" SET
  subject = 'Your credential expires soon',
  body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#F7F3E8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#263633;line-height:1.6;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#F7F3E8;"><tr><td align="center" style="padding:32px 16px;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;width:100%;background-color:#FFFFFF;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(23,74,67,0.06);border:1px solid #E5DFCF;"><tr><td style="background-color:#174A43;padding:28px 32px;text-align:center;"><div style="font-family:Georgia,serif;font-size:24px;font-weight:700;color:#FFFFFF;">MyZipVault</div><div style="font-size:11px;font-weight:600;color:#D98F78;letter-spacing:2.5px;text-transform:uppercase;margin-top:6px;">Credential Expiring</div></td></tr><tr><td style="padding:36px;font-size:15px;color:#263633;"><p style="margin:0 0 16px;">Hello {{candidate_name}},</p><p style="margin:0 0 16px;color:#5C6B66;">Your credential <strong style="color:#174A43;">{{document_name}}</strong> will expire on <strong style="color:#D98F78;">{{expiry_date}}</strong>. Please renew it to keep your profile up to date.</p><div style="text-align:center;margin:28px 0;"><a href="{{login_link}}" style="background-color:#174A43;color:#FFFFFF;padding:14px 32px;border-radius:10px;text-decoration:none;font-weight:600;display:inline-block;font-size:15px;">Renew Credential</a></div></td></tr><tr><td style="padding:0 36px 20px;"><table width="100%" style="border-top:1px solid #E5DFCF;padding-top:20px;"><tr><td style="font-size:12px;color:#8B9994;text-align:center;">HIPAA Aligned · 256-bit Encryption · BAA Available</td></tr></table></td></tr></table></td></tr></table></body></html>'
WHERE template_key = 'credential_expiry_warning';

-- 6. credit_low_warning / low_credit_alert
UPDATE "EmailTemplate" SET
  subject = 'Your credit balance is low',
  body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#F7F3E8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#263633;line-height:1.6;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#F7F3E8;"><tr><td align="center" style="padding:32px 16px;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;width:100%;background-color:#FFFFFF;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(23,74,67,0.06);border:1px solid #E5DFCF;"><tr><td style="background-color:#174A43;padding:28px 32px;text-align:center;"><div style="font-family:Georgia,serif;font-size:24px;font-weight:700;color:#FFFFFF;">MyZipVault</div><div style="font-size:11px;font-weight:600;color:#D98F78;letter-spacing:2.5px;text-transform:uppercase;margin-top:6px;">Low Credits</div></td></tr><tr><td style="padding:36px;font-size:15px;color:#263633;"><p style="margin:0 0 16px;">Hello {{user_name}},</p><p style="margin:0 0 16px;color:#5C6B66;">Your credit balance is running low. You currently have <strong style="color:#D98F78;">{{credit_balance}}</strong> credits remaining.</p><div style="text-align:center;margin:28px 0;"><a href="{{login_link}}" style="background-color:#174A43;color:#FFFFFF;padding:14px 32px;border-radius:10px;text-decoration:none;font-weight:600;display:inline-block;font-size:15px;">Buy Credits</a></div></td></tr><tr><td style="padding:0 36px 20px;"><table width="100%" style="border-top:1px solid #E5DFCF;padding-top:20px;"><tr><td style="font-size:12px;color:#8B9994;text-align:center;">HIPAA Aligned · 256-bit Encryption · BAA Available</td></tr></table></td></tr></table></td></tr></table></body></html>'
WHERE template_key IN ('credit_low_warning', 'low_credit_alert');

-- 7. document_unlocked
UPDATE "EmailTemplate" SET
  subject = 'Your document has been unlocked',
  body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#F7F3E8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#263633;line-height:1.6;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#F7F3E8;"><tr><td align="center" style="padding:32px 16px;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;width:100%;background-color:#FFFFFF;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(23,74,67,0.06);border:1px solid #E5DFCF;"><tr><td style="background-color:#174A43;padding:28px 32px;text-align:center;"><div style="font-family:Georgia,serif;font-size:24px;font-weight:700;color:#FFFFFF;">MyZipVault</div><div style="font-size:11px;font-weight:600;color:#D98F78;letter-spacing:2.5px;text-transform:uppercase;margin-top:6px;">Document Unlocked</div></td></tr><tr><td style="padding:36px;font-size:15px;color:#263633;"><p style="margin:0 0 16px;">Hello {{recruiter_name}},</p><p style="margin:0 0 16px;color:#5C6B66;">A candidate has unlocked their <strong style="color:#174A43;">{{document_type}}</strong> for your review. You can now access it from your dashboard.</p><div style="text-align:center;margin:28px 0;"><a href="{{login_link}}" style="background-color:#174A43;color:#FFFFFF;padding:14px 32px;border-radius:10px;text-decoration:none;font-weight:600;display:inline-block;font-size:15px;">View Document</a></div></td></tr><tr><td style="padding:0 36px 20px;"><table width="100%" style="border-top:1px solid #E5DFCF;padding-top:20px;"><tr><td style="font-size:12px;color:#8B9994;text-align:center;">HIPAA Aligned · 256-bit Encryption · BAA Available</td></tr></table></td></tr></table></td></tr></table></body></html>'
WHERE template_key = 'document_unlocked';

-- 8. manager_invite
UPDATE "EmailTemplate" SET
  subject = 'You''ve been invited to join MyZipVault',
  body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#F7F3E8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#263633;line-height:1.6;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#F7F3E8;"><tr><td align="center" style="padding:32px 16px;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;width:100%;background-color:#FFFFFF;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(23,74,67,0.06);border:1px solid #E5DFCF;"><tr><td style="background-color:#174A43;padding:28px 32px;text-align:center;"><div style="font-family:Georgia,serif;font-size:24px;font-weight:700;color:#FFFFFF;">MyZipVault</div><div style="font-size:11px;font-weight:600;color:#D98F78;letter-spacing:2.5px;text-transform:uppercase;margin-top:6px;">Team Invitation</div></td></tr><tr><td style="padding:36px;font-size:15px;color:#263633;"><p style="margin:0 0 16px;">Hello {{invitee_name}},</p><p style="margin:0 0 16px;color:#5C6B66;"><strong style="color:#174A43;">{{inviter_name}}</strong> has invited you to join their organization on MyZipVault. Click below to set up your account.</p><div style="text-align:center;margin:28px 0;"><a href="{{invite_link}}" style="background-color:#174A43;color:#FFFFFF;padding:14px 32px;border-radius:10px;text-decoration:none;font-weight:600;display:inline-block;font-size:15px;">Accept Invitation</a></div></td></tr><tr><td style="padding:0 36px 20px;"><table width="100%" style="border-top:1px solid #E5DFCF;padding-top:20px;"><tr><td style="font-size:12px;color:#8B9994;text-align:center;">HIPAA Aligned · 256-bit Encryption · BAA Available</td></tr></table></td></tr></table></td></tr></table></body></html>'
WHERE template_key = 'manager_invite';

-- 9. reference_request
UPDATE "EmailTemplate" SET
  subject = 'Reference request from {{candidate_name}}',
  body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#F7F3E8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#263633;line-height:1.6;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#F7F3E8;"><tr><td align="center" style="padding:32px 16px;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;width:100%;background-color:#FFFFFF;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(23,74,67,0.06);border:1px solid #E5DFCF;"><tr><td style="background-color:#174A43;padding:28px 32px;text-align:center;"><div style="font-family:Georgia,serif;font-size:24px;font-weight:700;color:#FFFFFF;">MyZipVault</div><div style="font-size:11px;font-weight:600;color:#D98F78;letter-spacing:2.5px;text-transform:uppercase;margin-top:6px;">Reference Request</div></td></tr><tr><td style="padding:36px;font-size:15px;color:#263633;"><p style="margin:0 0 16px;">Hello {{reference_name}},</p><p style="margin:0 0 16px;color:#5C6B66;"><strong style="color:#174A43;">{{candidate_name}}</strong> has requested you to provide a professional reference. Please click below to complete the reference form.</p><div style="text-align:center;margin:28px 0;"><a href="{{reference_link}}" style="background-color:#174A43;color:#FFFFFF;padding:14px 32px;border-radius:10px;text-decoration:none;font-weight:600;display:inline-block;font-size:15px;">Complete Reference</a></div><p style="margin:0 0 16px;color:#8B9994;font-size:13px;">No account needed — just click the button and fill out the form.</p></td></tr><tr><td style="padding:0 36px 20px;"><table width="100%" style="border-top:1px solid #E5DFCF;padding-top:20px;"><tr><td style="font-size:12px;color:#8B9994;text-align:center;">HIPAA Aligned · 256-bit Encryption · BAA Available</td></tr></table></td></tr></table></td></tr></table></body></html>'
WHERE template_key = 'reference_request';

-- 10. reference_reminder
UPDATE "EmailTemplate" SET
  subject = 'Reminder: Reference request from {{candidate_name}}',
  body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#F7F3E8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#263633;line-height:1.6;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#F7F3E8;"><tr><td align="center" style="padding:32px 16px;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;width:100%;background-color:#FFFFFF;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(23,74,67,0.06);border:1px solid #E5DFCF;"><tr><td style="background-color:#174A43;padding:28px 32px;text-align:center;"><div style="font-family:Georgia,serif;font-size:24px;font-weight:700;color:#FFFFFF;">MyZipVault</div><div style="font-size:11px;font-weight:600;color:#D98F78;letter-spacing:2.5px;text-transform:uppercase;margin-top:6px;">Reference Reminder</div></td></tr><tr><td style="padding:36px;font-size:15px;color:#263633;"><p style="margin:0 0 16px;">Hello {{reference_name}},</p><p style="margin:0 0 16px;color:#5C6B66;">This is a friendly reminder that <strong style="color:#174A43;">{{candidate_name}}</strong> is still waiting for your reference. Please click below to complete it.</p><div style="text-align:center;margin:28px 0;"><a href="{{reference_link}}" style="background-color:#174A43;color:#FFFFFF;padding:14px 32px;border-radius:10px;text-decoration:none;font-weight:600;display:inline-block;font-size:15px;">Complete Reference</a></div></td></tr><tr><td style="padding:0 36px 20px;"><table width="100%" style="border-top:1px solid #E5DFCF;padding-top:20px;"><tr><td style="font-size:12px;color:#8B9994;text-align:center;">HIPAA Aligned · 256-bit Encryption · BAA Available</td></tr></table></td></tr></table></td></tr></table></body></html>'
WHERE template_key = 'reference_reminder';

-- 11-15. VaultSign templates (completed, declined, expired, reminder, voided)
UPDATE "EmailTemplate" SET
  subject = CASE template_key
    WHEN 'vaultsign_completed' THEN 'Document signed successfully'
    WHEN 'vaultsign_declined' THEN 'Document signing declined'
    WHEN 'vaultsign_expired' THEN 'Document signing expired'
    WHEN 'vaultsign_reminder' THEN 'Reminder: Document needs your signature'
    WHEN 'vaultsign_voided' THEN 'Document signing voided'
  END,
  body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#F7F3E8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#263633;line-height:1.6;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#F7F3E8;"><tr><td align="center" style="padding:32px 16px;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;width:100%;background-color:#FFFFFF;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(23,74,67,0.06);border:1px solid #E5DFCF;"><tr><td style="background-color:#174A43;padding:28px 32px;text-align:center;"><div style="font-family:Georgia,serif;font-size:24px;font-weight:700;color:#FFFFFF;">MyZipVault</div><div style="font-size:11px;font-weight:600;color:#D98F78;letter-spacing:2.5px;text-transform:uppercase;margin-top:6px;">VaultSign Update</div></td></tr><tr><td style="padding:36px;font-size:15px;color:#263633;"><p style="margin:0 0 16px;">Hello {{signer_name}},</p><p style="margin:0 0 16px;color:#5C6B66;">The document <strong style="color:#174A43;">{{document_title}}</strong> has a status update: <strong>{{status}}</strong>.</p><div style="text-align:center;margin:28px 0;"><a href="{{login_link}}" style="background-color:#174A43;color:#FFFFFF;padding:14px 32px;border-radius:10px;text-decoration:none;font-weight:600;display:inline-block;font-size:15px;">View Document</a></div></td></tr><tr><td style="padding:0 36px 20px;"><table width="100%" style="border-top:1px solid #E5DFCF;padding-top:20px;"><tr><td style="font-size:12px;color:#8B9994;text-align:center;">HIPAA Aligned · 256-bit Encryption · BAA Available</td></tr></table></td></tr></table></td></tr></table></body></html>'
WHERE template_key IN ('vaultsign_completed', 'vaultsign_declined', 'vaultsign_expired', 'vaultsign_reminder', 'vaultsign_voided');

-- 16. welcome_client
UPDATE "EmailTemplate" SET
  subject = 'Welcome to MyZipVault',
  body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#F7F3E8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#263633;line-height:1.6;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#F7F3E8;"><tr><td align="center" style="padding:32px 16px;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;width:100%;background-color:#FFFFFF;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(23,74,67,0.06);border:1px solid #E5DFCF;"><tr><td style="background-color:#174A43;padding:28px 32px;text-align:center;"><div style="font-family:Georgia,serif;font-size:24px;font-weight:700;color:#FFFFFF;">MyZipVault</div><div style="font-size:11px;font-weight:600;color:#D98F78;letter-spacing:2.5px;text-transform:uppercase;margin-top:6px;">Welcome</div></td></tr><tr><td style="padding:36px;font-size:15px;color:#263633;"><p style="margin:0 0 16px;">Hello {{client_name}},</p><p style="margin:0 0 16px;color:#5C6B66;">Welcome to MyZipVault — the professional network built exclusively for healthcare. Start by setting up your organization profile and posting your first job.</p><div style="text-align:center;margin:28px 0;"><a href="{{login_link}}" style="background-color:#174A43;color:#FFFFFF;padding:14px 32px;border-radius:10px;text-decoration:none;font-weight:600;display:inline-block;font-size:15px;">Get Started</a></div></td></tr><tr><td style="padding:0 36px 20px;"><table width="100%" style="border-top:1px solid #E5DFCF;padding-top:20px;"><tr><td style="font-size:12px;color:#8B9994;text-align:center;">HIPAA Aligned · 256-bit Encryption · BAA Available</td></tr></table></td></tr></table></td></tr></table></body></html>'
WHERE template_key = 'welcome_client';

COMMIT;

-- Verification
SELECT
  template_key,
  CASE
    WHEN body LIKE '%#174A43%' AND body LIKE '%#F7F3E8%' AND body LIKE '%#D98F78%' THEN '✅ CRM Design'
    ELSE '❌ Old Design'
  END AS design_status
FROM "EmailTemplate"
ORDER BY template_key;
