-- ════════════════════════════════════════════════════════════════════
-- COMPREHENSIVE DATA VERIFICATION SCRIPT (CORRECTED: CamelCase)
-- Run this in Supabase SQL Editor to verify no data is missing.
--
-- This database uses CamelCase table names (Organization, User, etc.)
-- matching Prisma's default behavior (no @@map directives in schema).
-- ════════════════════════════════════════════════════════════════════

SELECT 'AdminPermission' AS table_name, count(*) AS row_count FROM "AdminPermission"
UNION ALL SELECT 'Announcement', count(*) FROM "Announcement"
UNION ALL SELECT 'ApiKey', count(*) FROM "ApiKey"
UNION ALL SELECT 'AuditLog', count(*) FROM "AuditLog"
UNION ALL SELECT 'AutomatedRule', count(*) FROM "AutomatedRule"
UNION ALL SELECT 'Banner', count(*) FROM "Banner"
UNION ALL SELECT 'CalendarAvailability', count(*) FROM "CalendarAvailability"
UNION ALL SELECT 'CalendarShare', count(*) FROM "CalendarShare"
UNION ALL SELECT 'CallLog', count(*) FROM "CallLog"
UNION ALL SELECT 'CallSchedule', count(*) FROM "CallSchedule"
UNION ALL SELECT 'CandidateChecklistResponse', count(*) FROM "CandidateChecklistResponse"
UNION ALL SELECT 'CandidateProfile', count(*) FROM "CandidateProfile"
UNION ALL SELECT 'CandidateReference', count(*) FROM "CandidateReference"
UNION ALL SELECT 'ChecklistRequest', count(*) FROM "ChecklistRequest"
UNION ALL SELECT 'ChecklistTemplate', count(*) FROM "ChecklistTemplate"
UNION ALL SELECT 'ConsentShare', count(*) FROM "ConsentShare"
UNION ALL SELECT 'Credential', count(*) FROM "Credential"
UNION ALL SELECT 'CreditTransaction', count(*) FROM "CreditTransaction"
UNION ALL SELECT 'DocumentFlag', count(*) FROM "DocumentFlag"
UNION ALL SELECT 'DocumentVerification', count(*) FROM "DocumentVerification"
UNION ALL SELECT 'EmailCampaign', count(*) FROM "EmailCampaign"
UNION ALL SELECT 'EmailCampaignRecipient', count(*) FROM "EmailCampaignRecipient"
UNION ALL SELECT 'EmailTemplate', count(*) FROM "EmailTemplate"
UNION ALL SELECT 'FeatureFlag', count(*) FROM "FeatureFlag"
UNION ALL SELECT 'InviteToken', count(*) FROM "InviteToken"
UNION ALL SELECT 'Invoice', count(*) FROM "Invoice"
UNION ALL SELECT 'Notification', count(*) FROM "Notification"
UNION ALL SELECT 'Organization', count(*) FROM "Organization"
UNION ALL SELECT 'PendingReminder', count(*) FROM "PendingReminder"
UNION ALL SELECT 'PlatformSetting', count(*) FROM "PlatformSetting"
UNION ALL SELECT 'RecruiterAvailability', count(*) FROM "RecruiterAvailability"
UNION ALL SELECT 'RecruiterLead', count(*) FROM "RecruiterLead"
UNION ALL SELECT 'ReferenceDeletionRequest', count(*) FROM "ReferenceDeletionRequest"
UNION ALL SELECT 'ReferenceQuestion', count(*) FROM "ReferenceQuestion"
UNION ALL SELECT 'ReferenceResponse', count(*) FROM "ReferenceResponse"
UNION ALL SELECT 'Resume', count(*) FROM "Resume"
UNION ALL SELECT 'ShareRequest', count(*) FROM "ShareRequest"
UNION ALL SELECT 'ShiftRequest', count(*) FROM "ShiftRequest"
UNION ALL SELECT 'Skill', count(*) FROM "Skill"
UNION ALL SELECT 'SkillRating', count(*) FROM "SkillRating"
UNION ALL SELECT 'SystemErrorLog', count(*) FROM "SystemErrorLog"
UNION ALL SELECT 'UnlockedDocument', count(*) FROM "UnlockedDocument"
UNION ALL SELECT 'User', count(*) FROM "User"
UNION ALL SELECT 'VaultSignDocument', count(*) FROM "VaultSignDocument"
UNION ALL SELECT 'VaultSignReminder', count(*) FROM "VaultSignReminder"
UNION ALL SELECT 'VaultSignSigner', count(*) FROM "VaultSignSigner"
UNION ALL SELECT 'VaultSignTemplate', count(*) FROM "VaultSignTemplate"
ORDER BY table_name;
